development:
  adapter: sqlite3
  database: prelaunchr_development
  host: localhost

test:
  adapter: sqlite3
  database: prelaunchr_test
  host: localhost
  
production:
  adapter: postgresql
  database: prelaunchr
  host: localhost